### ISSUE TITLE
jekyll can not run as no root

### ISSUE THREAD

**Issue by Syleechan** [JV-conseil/jekyll-docker#17]
Hi, when I run the jekyll as no root user with docker desktop, the log shows the error log
```java
2023-09-05 14:08:36 /usr/jekyll/bin/jekyll: exec: line 16: /usr/local/bundle/bin/jekyll: not found
``` 

 do you meet the follow issue? And my dockfile as follow

```dockerfile
FROM jekyll/jekyll:latest

ENV KYLIN_HOME=/srv/jekyll/kylin
#for document dir files, please download them rather than pull from git
COPY --chown=jekyll:jekyll document $KYLIN_HOME

WORKDIR $KYLIN_HOME/website

RUN cd $KYLIN_HOME \
    && rm -rf .git/

USER jekyll
CMD ["sh", "-c", "jekyll serve -P 4000 -H 0.0.0.0 -w"]
```

**Comment by Syleechan** [comment]
Thanks very much if you can help on it.

**Comment by JV-conseil** [comment]
Hi @Syleechan 👋

You are confusing Dockers images.

This repo Docker image is `jvconseil/jekyll-docker` available at <https://hub.docker.com/r/jvconseil/jekyll-docker>.

Your Dockerfile sample `FROM jekyll/jekyll:latest` points to `jekyll/jekyll` available at <https://hub.docker.com/r/jekyll/jekyll>.
